repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
        args:
        - --no-banner
        - --redact=0

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix-only, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format